"""Strategies domain: shared store for free-form strategy prompts.

A "strategy" is a free-form natural-language trading prompt (e.g. generated by
the Discord bot) saved under a short share code so it can be viewed on the
website and run through the existing backtest workflow. The store is a simple
on-disk JSON file so it is visible across processes (the API server and the
standalone Discord bot both run on the same host).
"""
