export { auditDecision, tierFor, AuditSchema } from './auditor.js';
export type { Audit, AuditResult, AuditTier, AuditOutcome, AuditDeps } from './auditor.js';
export { EdgarPollerAgent, EarningsReaderAgent } from './agents.js';
export type { PipelineDeps, NotifyLike } from './agents.js';
export { universeFor, edgarWatchable, US_UNIVERSE, CRYPTO_UNIVERSE, IN_UNIVERSE } from './universe.js';
export type { UniverseEntry } from './universe.js';
export { PositionGuardianAgent, evaluateExit, pnlPct, DRIFT_EXIT } from './guardian.js';
export type { ExitRule, ExitReason, ExitDecision } from './guardian.js';
export { DailySummary, collectSummary, summaryBody } from './summary.js';
export type { DaySummary } from './summary.js';
export { NewsScoutAgent, interleave, SIG_NEWS } from './news.js';
export type { NewsDeps, ScoutedStory } from './news.js';
export { NewsTraderAgent, gateNewsTrade, DEFAULT_NEWS_RULE } from './news-trader.js';
export type { NewsTradeRule, NewsGateResult, NewsRejectReason, NewsTraderDeps, Venue } from './news-trader.js';
export { closedTrades, summarise, maxDrawdown, compareToBenchmark, byConfidence, bySource, performanceReport } from './evaluator.js';
export type { ClosedTrade, Performance, BenchmarkResult, TierBucket } from './evaluator.js';
export { evaluateWatch, readConditions, driftConditions, newsConditions, newFilingSince, opposingNewsSince, WatchConditionSchema } from './watch.js';
export type { WatchCondition, WatchContext, WatchBreak } from './watch.js';
